import os
import shutil
import json

# Path to the catalog layout generated by Apple's runner
catalog_path = 'extracted_raw/catalog.json'
output_folder = 'All_Original_Images'
os.makedirs(output_folder, exist_ok=True)

if os.path.exists(catalog_path):
    with open(catalog_path) as f:
        data = json.load(f)
        print("--- EXTRACTING AUTHENTIC FILE MAPPINGS ---")
        for item in data:
            if 'Name' in item and item.get('RenditionType') == 'Bitmap':
                name = item['Name']
                # Create a temporary, structured asset folder
                imageset_dir = f'Assets.xcassets/{name}.imageset'
                os.makedirs(imageset_dir, exist_ok=True)
                
                # Setup mapping
                contents = {'images': [{'idiom': 'universal', 'filename': f'{name}.png'}], 'info': {'version': 1, 'author': 'xcode'}}
                with open(f'{imageset_dir}/Contents.json', 'w') as jf:
                    json.dump(contents, jf)
                
                # Write a standard placeholder for now to fetch the file keys safely
                with open(f'{imageset_dir}/{name}.png', 'wb') as f_dummy:
                    f_dummy.write(b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15c4\x00\x00\x00\rIDATx\x9cc`\x00\x01\x00\x00\x0c\x00\x01\x04\x1e\xe3\xa8\x00\x00\x00\x00IEND\xaeB`\x82')
                
                # Copy the layout file templates to our download folder
                shutil.copy(f'{imageset_dir}/Contents.json', f'{output_folder}/{name}_Contents.json')
